# numpy.array

In [1]:
import numpy

In [2]:
numpy.__version__

'1.16.4'

In [3]:
import numpy as np

In [4]:
np.__version__

'1.16.4'

### python List的特点

In [5]:
L = [i for i in range(10)]
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [6]:
L(4)

TypeError: 'list' object is not callable

In [7]:
L[4]

4

In [8]:
L[4] = 100
L

[0, 1, 2, 3, 100, 5, 6, 7, 8, 9]

In [9]:
L [5] = "Hello world"

In [10]:
L

[0, 1, 2, 3, 100, 'Hello world', 6, 7, 8, 9]

In [11]:
import array

In [12]:
arr = array.array('i', [i for i in range(10)])

In [13]:
arr

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
arr[5]

5

In [15]:
arr[5] = 100

In [16]:
arr

array('i', [0, 1, 2, 3, 4, 100, 6, 7, 8, 9])

In [17]:
arr[5] = "Hello world"

TypeError: an integer is required (got type str)

### numpy.array

In [18]:
nparr = np.array([i for i in range(10)])

In [19]:
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
nparr[5]

5

In [21]:
nparr[5] = 100

In [22]:
nparr

array([  0,   1,   2,   3,   4, 100,   6,   7,   8,   9])

In [23]:
nparr[5] = 'Hello world'

ValueError: invalid literal for int() with base 10: 'Hello world'

In [24]:
nparr.dtype

dtype('int32')

In [25]:
nparr[5] = 5.0

In [26]:
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
nparr[4] = 3.86
nparr

NameError: name 'nparr' is not defined

In [3]:
nparr = np.array([i for i in range(10)])
nparr

NameError: name 'np' is not defined

In [4]:
import numpy as np

In [5]:
nparr = np.array([i for in i range(10)])

SyntaxError: invalid syntax (<ipython-input-5-727bd3554c68>, line 1)

In [6]:
nparr = np.array([i for i in range(10)])

In [7]:
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
nparr[4] = 5.0
nparr

array([0, 1, 2, 3, 5, 5, 6, 7, 8, 9])

In [9]:
nparr[4] = 3.98

In [10]:
nparr

array([0, 1, 2, 3, 3, 5, 6, 7, 8, 9])

### 其他创建numpy.array的方法

In [1]:
np.zeros(10)

NameError: name 'np' is not defined

In [2]:
import numpy as np


In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
np.zeros(10).dtype

dtype('float64')

In [5]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [6]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.full(shape=3)

## numpy.array 中的运算

#### 给定一个向量，让向量中的每一个数乘以2
a = (0,1,2)
a * 2 = (0,2,4)

In [1]:
n = 10
L = [i for i in range(n)]

In [2]:
2 * L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]